Repository woowacourse-teams/2025-Fit-toring, pull requests merged in 2025-08, with the labels that each got.

#233 [FEAT] 회원가입 페이지 폼 UI 구현
  backend/fittoring/docker-compose.yml
  backend/fittoring/src/main/java/fittoring/aspect/LogAspect.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/resources/application.yml
  frontend/package.json
  frontend/src/common/assets/images/blind.svg
  frontend/src/common/assets/images/notBlind.svg
  frontend/src/common/components/Button/Button.tsx
  frontend/src/common/components/FormField/FormField.tsx
  frontend/src/common/components/Input/Input.tsx
  frontend/src/pages/booking/components/BookingForm/BookingForm.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/Slogan/Slogan.tsx
  frontend/src/pages/signup/Signup.tsx
  frontend/src/pages/signup/components/PasswordFields/PasswordFields.tsx
  frontend/src/pages/signup/components/PhoneFields/PhoneFields.tsx
  frontend/src/pages/signup/components/SignupForm/SignupForm.stories.tsx
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
  frontend/src/pages/signup/components/SignupIntro/SignupIntro.tsx
  frontend/src/pages/signup/components/UserIdField/UserIdField.tsx
  frontend/src/pages/signup/components/UserInfoFields/UserInfoFields.tsx
Labels: ❄️ FE, ☘️ feat

#239 [FIX] 에러 로그에 에러 클래스 이름 추가
  backend/fittoring/src/main/java/fittoring/aspect/LogAspect.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
Labels: ✨ BE, 🔧 fix

#243 [MERGE] 배포
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/aspect/LogAspect.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/exception/SystemErrorMessage.java
  backend/fittoring/src/main/resources/application.yml
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/common/assets/images/menuBar.svg
  frontend/src/common/components/FormField/FormField.tsx
  frontend/src/common/components/Input/Input.tsx
  frontend/src/common/constants/url.ts
  frontend/src/pages/booking/components/BookingForm/BookingForm.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/Slogan/Slogan.tsx
  frontend/src/pages/mentoringCreate/MentoringCreate.tsx
  frontend/src/pages/mentoringCreate/components/BaseInfoSection/BaseInfoSection.stories.tsx
  frontend/src/pages/mentoringCreate/components/BaseInfoSection/BaseInfoSection.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.stories.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateHeader/MentoringCreateHeader.stories.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateHeader/MentoringCreateHeader.tsx
  frontend/src/pages/mentoringCreate/components/TitleSeparator/TitleSeparator.stories.tsx
  frontend/src/pages/mentoringCreate/components/TitleSeparator/TitleSeparator.tsx
  frontend/src/pages/myPage/MyPage.tsx
  frontend/src/pages/myPage/components/MyPageHeader/MyPageHeader.stories.tsx
  frontend/src/pages/myPage/components/MyPageHeader/MyPageHeader.tsx
Labels: 🧻 merge

#236 [FEAT] 마이페이지 메뉴 드롭다운 UI
  frontend/src/pages/myPage/components/MenuDropDown/MenuDropDown.stories.tsx
  frontend/src/pages/myPage/components/MenuDropDown/MenuDropDown.tsx
  frontend/src/pages/myPage/components/MyPageHeader/MyPageHeader.tsx
Labels: ❄️ FE, ☘️ feat

#242 [FEAT] 전화번호 인증번호 발송 기능 구현
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/InvalidPhoneException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Phone.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/PhoneVerification.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/PhoneVerificationRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/CodeGenerator.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/PhoneVerificationFacadeService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/PhoneVerificationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/LongSmsSendClientDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/ShortSmsSendClientDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsMessageFormatter.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsRestClientService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/VerificationCodeGenerator.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/AuthController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/VerifyPhoneNumberRequest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/SmsRestClientIntegrationTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/AuthControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReservationControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/model/PhoneTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/PhoneVerificationFacadeServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/PhoneVerificationServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/infra/CodeGeneratorStub.java
  backend/fittoring/src/test/java/fittoring/mentoring/infra/SmsRestClientServiceTest.java
Labels: ✨ BE, ☘️ feat

#244 [FEAT] 마이페이지 프로필 UI
  frontend/src/common/mock/browser.ts
  frontend/src/common/mock/handlers.ts
  frontend/src/common/mock/handlers/handlers.ts
  frontend/src/common/mock/mentoring/data.ts
  frontend/src/common/mock/mentoring/handlers.ts
  frontend/src/common/mock/myProfile/data.ts
  frontend/src/common/mock/myProfile/handlers.ts
  frontend/src/common/mock/server.ts
  frontend/src/pages/myPage/MyPage.tsx
  frontend/src/pages/myPage/apis/getMyProfile.tsx
  frontend/src/pages/myPage/components/MenuDropDown/MenuDropDown.tsx
  frontend/src/pages/myPage/components/MyPageHeader/MyPageHeader.tsx
  frontend/src/pages/myPage/components/MyProfile/MyProfile.stories.tsx
  frontend/src/pages/myPage/components/MyProfile/MyProfile.tsx
  frontend/src/pages/myPage/types/myProfile.ts
Labels: ❄️ FE, ☘️ feat

#247 [FEAT] 전문 분야 폼 UI
  frontend/src/common/apis/getSpecialties.ts
  frontend/src/common/mock/common/data.ts
  frontend/src/common/mock/common/handlers.ts
  frontend/src/common/mock/handlers.ts
  frontend/src/common/types/Specialty.ts
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringCreate/components/SpecialtySection/SpecialtySection.stories.tsx
  frontend/src/pages/mentoringCreate/components/SpecialtySection/SpecialtySection.tsx
  frontend/src/pages/mentoringCreate/components/SpecialtyTag/SpecialtyTag.stories.tsx
  frontend/src/pages/mentoringCreate/components/SpecialtyTag/SpecialtyTag.tsx
Labels: ❄️ FE, ☘️ feat

#248 [FEAT] 인증번호 확인 기능 구현
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/InvalidPhoneVerificationException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/PhoneVerification.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/PhoneVerificationRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/PhoneVerificationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/AuthController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/VerificationCodeRequest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/AuthControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/PhoneVerificationServiceTest.java
Labels: ✨ BE, ☘️ feat

#254 [FEAT] 자격증 폼 UI
  frontend/src/common/assets/images/certificateUploadIcon.svg
  frontend/src/common/assets/images/deleteIcon.svg
  frontend/src/common/assets/images/downIcon.svg
  frontend/src/common/hooks/usePreviewImage.ts
  frontend/src/pages/mentoringCreate/components/CertificateInput/CertificateInput.tsx
  frontend/src/pages/mentoringCreate/components/CertificateSection/CertificateSection.stories.tsx
  frontend/src/pages/mentoringCreate/components/CertificateSection/CertificateSection.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringCreate/components/ProfileSection/ProfileSection.tsx
  frontend/src/pages/mentoringCreate/components/TitleSeparator/TitleSeparator.tsx
Labels: ❄️ FE, ☘️ feat

#256 [FEAT] 멘토링 개설 기능 구현
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/config/S3Configuration.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Certificate.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/CertificateType.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/ImageType.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Status.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/CategoryRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/CertificateService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ImageService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/RegisterMentoringDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/S3Uploader.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/exception/InfraErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/exception/S3UploadException.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/exception/SmsException.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MentoringController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/CertificateInfo.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringRequest.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringSummaryResponse.java
  backend/fittoring/src/main/resources/data.sql
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReservationControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
Labels: ✨ BE, ☘️ feat

#286 [FIX] 테스트용 기본 데이터 버그 픽스
  backend/fittoring/src/main/resources/data.sql
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/PhoneVerificationServiceTest.java
Labels: ✨ BE, 🔧 fix

#297 [FEAT] 멘토링 조회 요청 인증 제외
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/java/fittoring/config/auth/AuthenticationInterceptor.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/S3Uploader.java
Labels: ✨ BE, ☘️ feat, 🔧 fix

#288 [FEAT] 개설한 멘토링에 대한 예약 목록 API 연결
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/common/mock/createdMentoring/data.ts
  frontend/src/common/mock/createdMentoring/handlers.ts
  frontend/src/common/mock/handlers.ts
  frontend/src/pages/CreatedMentoring/CreatedMentoring.tsx
  frontend/src/pages/CreatedMentoring/apis/getMentoringApplicationList.tsx
  frontend/src/pages/CreatedMentoring/components/MentoringApplicationItem/MentoringApplicationItem.stories.tsx
  frontend/src/pages/CreatedMentoring/components/MentoringApplicationList/MentoringApplicationList.stories.tsx
  frontend/src/pages/CreatedMentoring/types/mentoringApplication.ts
  frontend/src/pages/myPage/apis/getMyProfile.tsx
Labels: ❄️ FE, ☘️ feat

#300 [FEAT] 로그인 API 연결
  frontend/src/common/apis/apiClient.ts
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/common/mock/handlers.ts
  frontend/src/common/mock/login/handler.ts
  frontend/src/pages/login/apis/postLogin.ts
  frontend/src/pages/login/components/LoginForm/LoginForm.tsx
Labels: ❄️ FE, ☘️ feat

#291 [FEAT] 메인 페이지 선택한 전문 분야
  frontend/src/common/mock/mentoring/data.ts
  frontend/src/common/mock/mentoring/handlers.ts
  frontend/src/common/styles/reset.ts
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/SpecialtyCheckbox/SpecialtyCheckbox.tsx
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.tsx
Labels: ❄️ FE, ☘️ feat

#296 [FEAT] 멘토링 개설 페이지 API 연결
  frontend/.gitignore
  frontend/src/common/apis/apiClient.ts
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/common/mock/handlers.ts
  frontend/src/common/mock/members/data.ts
  frontend/src/common/mock/members/handlers.ts
  frontend/src/common/mock/mentoring/handlers.ts
  frontend/src/pages/mentoringCreate/apis/getUserInfo.ts
  frontend/src/pages/mentoringCreate/apis/postMentoringCreate.ts
  frontend/src/pages/mentoringCreate/components/BaseInfoSection/BaseInfoSection.stories.tsx
  frontend/src/pages/mentoringCreate/components/BaseInfoSection/BaseInfoSection.tsx
  frontend/src/pages/mentoringCreate/components/CertificateInput/CertificateInput.tsx
  frontend/src/pages/mentoringCreate/components/CertificateSection/CertificateSection.stories.tsx
  frontend/src/pages/mentoringCreate/components/CertificateSection/CertificateSection.tsx
  frontend/src/pages/mentoringCreate/components/DetailIntroduce/DetailIntroduce.stories.tsx
  frontend/src/pages/mentoringCreate/components/DetailIntroduce/DetailIntroduce.tsx
  frontend/src/pages/mentoringCreate/components/IntroduceSection/IntroduceSection.stories.tsx
  frontend/src/pages/mentoringCreate/components/IntroduceSection/IntroduceSection.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringCreate/components/ProfileSection/ProfileSection.stories.tsx
  frontend/src/pages/mentoringCreate/components/ProfileSection/ProfileSection.tsx
  frontend/src/pages/mentoringCreate/components/SpecialtySection/SpecialtySection.stories.tsx
  frontend/src/pages/mentoringCreate/components/SpecialtySection/SpecialtySection.tsx
  frontend/src/pages/mentoringCreate/components/types/certificateItem.ts
  frontend/src/pages/mentoringCreate/components/types/mentoringCreateFormData.ts
  frontend/src/pages/mentoringCreate/components/types/userInfoResponse.ts
Labels: ❄️ FE, ☘️ feat

#289 [FEAT] 예약 신청폼 사용자정보 인풋 제거 및 전화번호 전달 고지 체크박스 추가
  frontend/src/common/apis/getUserInfo.ts
  frontend/src/common/components/FormField/FormField.tsx
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/common/mock/common/data.ts
  frontend/src/common/mock/common/handlers.ts
  frontend/src/common/mock/handlers.ts
  frontend/src/common/types/userInfo.ts
  frontend/src/pages/booking/components/BookingForm/BookingForm.tsx
  frontend/src/pages/booking/components/BookingSummarySection/BookingSummarySection.tsx
  frontend/src/pages/booking/components/Checkbox/Checkbox.stories.tsx
  frontend/src/pages/booking/components/Checkbox/Checkbox.tsx
  frontend/src/pages/booking/components/CompleteModal/CompleteModal.stories.tsx
  frontend/src/pages/booking/components/CompleteModal/CompleteModal.tsx
  frontend/src/pages/booking/types/BookingResponse.ts
  frontend/src/pages/mentoringCreate/components/SpecialtySection/SpecialtySection.stories.tsx
Labels: ❄️ FE, ☘️ feat

#307 [FEAT] 멘토링 개설 폼 유효성 검사 추가
  frontend/src/common/components/Input/Input.tsx
  frontend/src/pages/mentoringCreate/components/BaseInfoSection/BaseInfoSection.stories.tsx
  frontend/src/pages/mentoringCreate/components/BaseInfoSection/BaseInfoSection.tsx
  frontend/src/pages/mentoringCreate/components/CertificateInput/CertificateInput.tsx
  frontend/src/pages/mentoringCreate/components/DetailIntroduce/DetailIntroduce.tsx
  frontend/src/pages/mentoringCreate/components/IntroduceSection/IntroduceSection.stories.tsx
  frontend/src/pages/mentoringCreate/components/IntroduceSection/IntroduceSection.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringCreate/components/ProfileSection/ProfileSection.tsx
  frontend/src/pages/mentoringCreate/components/types/mentoringCreateFormData.ts
  frontend/src/pages/mentoringCreate/constants/career.ts
  frontend/src/pages/mentoringCreate/constants/introduce.ts
  frontend/src/pages/mentoringCreate/constants/price.ts
  frontend/src/pages/mentoringCreate/utils/careerValidator.ts
  frontend/src/pages/mentoringCreate/utils/introduceValidator.ts
  frontend/src/pages/mentoringCreate/utils/priceValidator.ts
Labels: ❄️ FE, ☘️ feat

#313 [REFACTOR] 개설한 멘토링 API 명세 변경에 따른 타입 및 데이터 수정
  frontend/src/App.tsx
  frontend/src/common/mock/createdMentoring/data.ts
  frontend/src/pages/createdMentoring/CreatedMentoring.tsx
  frontend/src/pages/createdMentoring/apis/getMentoringApplicationList.tsx
  frontend/src/pages/createdMentoring/components/ActionButtons/ActionButtons.stories.tsx
  frontend/src/pages/createdMentoring/components/ActionButtons/ActionButtons.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationItem/MentoringApplicationItem.stories.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationItem/MentoringApplicationItem.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationList/MentoringApplicationList.stories.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationList/MentoringApplicationList.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationStatus/MentoringApplicationStatus.stories.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationStatus/MentoringApplicationStatus.tsx
  frontend/src/pages/createdMentoring/components/PhoneNumber/PhoneNumber.stories.tsx
  frontend/src/pages/createdMentoring/components/PhoneNumber/PhoneNumber.tsx
  frontend/src/pages/createdMentoring/types/mentoringApplication.ts
  frontend/src/pages/createdMentoring/types/statusType.ts
Labels: ❄️ FE, ☘️ feat

#320 [FIX] Data.sql 핫픽스
  backend/fittoring/src/main/resources/data.sql
Labels: ✨ BE, ☘️ feat

#311 [FEAT] 참여한 멘토링 UI
  frontend/src/App.tsx
  frontend/src/common/components/MentoringApplicationStatus/MentoringApplicationStatus.stories.tsx
  frontend/src/common/components/MentoringApplicationStatus/MentoringApplicationStatus.tsx
  frontend/src/common/constants/url.ts
  frontend/src/common/types/statusType.ts
  frontend/src/pages/createdMentoring/CreatedMentoring.tsx
  frontend/src/pages/createdMentoring/components/ActionButtons/ActionButtons.stories.tsx
  frontend/src/pages/createdMentoring/components/ActionButtons/ActionButtons.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationItem/MentoringApplicationItem.tsx
  frontend/src/pages/createdMentoring/components/PhoneNumber/PhoneNumber.stories.tsx
  frontend/src/pages/createdMentoring/components/PhoneNumber/PhoneNumber.tsx
  frontend/src/pages/createdMentoring/types/mentoringApplication.ts
  frontend/src/pages/myPage/MyPage.tsx
  frontend/src/pages/myPage/components/MenuDropDown/MenuDropDown.tsx
  frontend/src/pages/participatedMentoring/MentoringItem/MentoringItem.stories.tsx
  frontend/src/pages/participatedMentoring/MentoringItem/MentoringItem.tsx
  frontend/src/pages/participatedMentoring/MentoringList/MentoringList.tsx
  frontend/src/pages/participatedMentoring/ParticipatedMentoring.tsx
  frontend/src/pages/participatedMentoring/ReviewButton/ReviewButton.stories.tsx
  frontend/src/pages/participatedMentoring/ReviewButton/ReviewButton.tsx
  frontend/src/pages/participatedMentoring/types/participatedMentoring.ts
Labels: ❄️ FE, ☘️ feat

#308 [FEAT] 로그인폼 유효성 검사
  frontend/.storybook/main.ts
  frontend/__tests__/BookingForm.test.tsx
  frontend/__tests__/usePasswordInput.test.ts
  frontend/__tests__/useUserIdInput.test.ts
  frontend/__tests__/useVerificationCodeInput.test.ts
  frontend/setupTests.ts
  frontend/src/common/constants/errorMessage.ts
  frontend/src/common/constants/id.ts
  frontend/src/common/constants/password.ts
  frontend/src/common/hooks/usePasswordInput.ts
  frontend/src/common/hooks/useUserIdInput.ts
  frontend/src/pages/login/components/LoginForm/LoginForm.tsx
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
  frontend/src/pages/signup/constants/errorMessage.ts
  frontend/src/pages/signup/hooks/usePasswordWithConfirmInput.ts
Labels: ❄️ FE, ☘️ feat

#337 [FIX] S3 이미지 업로더 오류 설정
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ImageService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/S3Uploader.java
Labels: ✨ BE, ☘️ feat

#334 [FEAT] 개설한 멘토링에 대한 예약 승인 및 거절
  frontend/src/common/apis/apiClient.ts
  frontend/src/common/components/MentoringApplicationStatus/MentoringApplicationStatus.tsx
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/common/mock/createdMentoring/data.ts
  frontend/src/common/mock/createdMentoring/handlers.ts
  frontend/src/common/mock/handlers.ts
  frontend/src/common/mock/myProfile/data.ts
  frontend/src/common/mock/myProfile/handlers.ts
  frontend/src/pages/createdMentoring/CreatedMentoring.tsx
  frontend/src/pages/createdMentoring/apis/getMenteePhoneNumber.ts
  frontend/src/pages/createdMentoring/apis/getMentoringApplicationList.ts
  frontend/src/pages/createdMentoring/apis/patchReservationStatus.ts
  frontend/src/pages/createdMentoring/components/ActionButtons/ActionButtons.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationItem/MentoringApplicationItem.tsx
  frontend/src/pages/createdMentoring/types/menteePhoneNumber.ts
  frontend/src/pages/createdMentoring/types/mentoringApplicationStatus.ts
  frontend/src/pages/myPage/apis/getMyProfile.tsx
  frontend/src/pages/myPage/components/MyProfile/MyProfile.tsx
  frontend/src/pages/myPage/types/myProfile.ts
Labels: ❄️ FE, ☘️ feat

#341 [FIX] 멘토링 상세 조회
  backend/fittoring/src/main/java/fittoring/config/auth/AuthenticationInterceptor.java
Labels: ✨ BE, 🔧 fix

#335 [FEAT] Sentry 설정
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-chromatic.yml
  .github/workflows/frontend-vitest.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/main.tsx
  frontend/src/pages/booking/components/BookingForm/BookingForm.tsx
  frontend/src/pages/login/components/LoginForm/LoginForm.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
  frontend/src/pages/signup/hooks/useUserIdDuplicateCheck.ts
  frontend/src/pages/signup/hooks/useVerificationCodeConfirm.ts
  frontend/src/pages/signup/hooks/useVerificationCodeRequest.ts
Labels: ❄️ FE, ☘️ feat

#345 [FEAT] GA 액션 및 라벨 수정
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.tsx
Labels: ❄️ FE, ☘️ feat

#351 [FIX] 페이지 url 수정 및 누락된 api 옵션 추가
  frontend/src/common/apis/getUserInfo.ts
  frontend/src/pages/myPage/components/MenuDropDown/MenuDropDown.tsx
Labels: ❄️ FE, 🔧 fix

#354 [DOCS] 최상위 README 추가
  README.md
Labels: 📄 docs

#355 [FIX] 멘토링 개설 버튼 추가, api 명세 변경에 따른 타입 및 데이터 수정
  frontend/src/common/components/FormField/FormField.tsx
  frontend/src/common/mock/common/data.ts
  frontend/src/common/types/userInfo.ts
  frontend/src/main.tsx
  frontend/src/pages/booking/components/BookingForm/BookingForm.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/HomeHeader/HomeHeader.tsx
  frontend/src/pages/home/components/Slogan/Slogan.tsx
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.tsx
  frontend/src/pages/login/components/LoginForm/LoginForm.tsx
  frontend/src/pages/login/components/LoginFormSection/LoginFormSection.tsx
  frontend/src/pages/mentoringCreate/components/ButtonSection/ButtonSection.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/myPage/components/MyProfile/MyProfile.tsx
  frontend/src/pages/signup/Signup.tsx
  frontend/src/pages/signup/components/AuthFooter/AuthFooter.tsx
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
Labels: ❄️ FE, 🔧 fix

#312 [FEAT] 관리자 자격증명 기능 구현
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/AlreadyProcessedCertificateException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/CertificateNotFoundException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/ForbiddenMemberException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/ImageNotFoundException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Certificate.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Member.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/MemberRole.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/CertificateRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/CertificateService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminCertificateController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/CertificateDetailResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/CertificateResponse.java
  backend/fittoring/src/main/resources/data.sql
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminCertificateControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/CertificateServiceTest.java
Labels: ✨ BE, ☘️ feat

#331 [FEAT] 멘토링 승인/거절 시 SMS 발송 기능 구현
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/NotFoundStatusException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Status.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringReservationFacadeService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/PhoneVerificationFacadeService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationNotificationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsMessageFormatter.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ReservationController.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReservationControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/model/StatusTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/PhoneVerificationFacadeServiceTest.java
Labels: ✨ BE, ☘️ feat

#360 [MERGE] 멘토 마이페이지(예약 현황 확인/승인/거절) 기능 release 브랜치 merge 요청
  .github/workflows/backend-ci.yml
  backend/fittoring/src/main/java/fittoring/config/auth/AuthenticationInterceptor.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/InvalidStatusException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/NotFoundReservationException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/NotFoundStatusException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Mentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Status.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ReservationRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringReservationFacadeService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/PhoneVerificationFacadeService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationNotificationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/MentorMentoringReservationResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/PhoneNumberResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/ReservationMenteeSmsDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/SmsReservationMessageDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsMessageFormatter.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ReservationController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ReservationCreateResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ReservationStatusUpdateRequest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReservationControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReviewControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/model/StatusTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/PhoneVerificationFacadeServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
Labels: ✨ BE, 🧻 merge

#362 [FIX] 자격증 없이 멘토링 개설 시 발생하던 버그 수정
  frontend/src/pages/mentoringCreate/components/CertificateSection/CertificateSection.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringCreate/components/types/certificateItem.ts
  frontend/src/pages/mentoringCreate/components/types/mentoringCreateFormData.ts
Labels: ❄️ FE, 🔧 fix

#364 [FIX] 개설한 멘토링에 대한 정보 api 응답 구조 변경
  frontend/src/pages/createdMentoring/apis/getMentoringApplicationList.ts
  frontend/src/pages/createdMentoring/types/mentoringApplication.ts
Labels: ❄️ FE, 🔧 fix

#366 [FIX] 관리자페이지 디버깅
  backend/back-office/components/Dashboard.tsx
  backend/back-office/components/LoginPage.tsx
  backend/back-office/services/certificateApi.ts
  backend/back-office/tsconfig.app.json
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/resources/static/web-admin/assets/index-DbAmRrn0.js
  backend/fittoring/src/main/resources/static/web-admin/assets/index-DbAmRrn0.js.map
Labels: 🔧 fix

#368 fix: 멘토링 예약 생성시 멘토에게 sms 문자를 보내도록 수정
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationNotificationService.java
Labels: ✨ BE, 🔧 fix

#369 [MERGE] 관리자페이지 디버깅
  backend/back-office/components/Dashboard.tsx
  backend/back-office/components/LoginPage.tsx
  backend/back-office/services/certificateApi.ts
  backend/back-office/tsconfig.app.json
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Review.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ReservationRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ReviewRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationNotificationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReviewService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/MemberReviewGetDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/MentoringReviewGetDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ReviewController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MemberReviewGetResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringReviewGetResponse.java
  backend/fittoring/src/main/resources/static/web-admin/assets/index-DbAmRrn0.js
  backend/fittoring/src/main/resources/static/web-admin/assets/index-DbAmRrn0.js.map
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReviewControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
  frontend/src/pages/createdMentoring/apis/getMentoringApplicationList.ts
  frontend/src/pages/createdMentoring/types/mentoringApplication.ts
  frontend/src/pages/mentoringCreate/components/CertificateSection/CertificateSection.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringCreate/components/types/certificateItem.ts
  frontend/src/pages/mentoringCreate/components/types/mentoringCreateFormData.ts
Labels: 🧻 merge

#380 [FIX] 서버에서 전달한 에러 메시지가 표시되지 않는 문제 수정
  frontend/src/common/apis/apiClient.ts
Labels: ❄️ FE, 🔧 fix

#386 [FEAT] 3차 스프린트 기능 수정 및 리팩터링
  backend/fittoring/src/main/java/fittoring/aspect/LogAspect.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/DuplicatePhoneException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/InvalidCertificateException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/MentoringAlreadyExistException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/CertificateType.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MemberRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/AuthService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/CertificateService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/resources/data.sql
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
Labels: ✨ BE, ☘️ feat

#387 [RELEASE]
  backend/back-office/components/Dashboard.tsx
  backend/back-office/components/LoginPage.tsx
  backend/back-office/components/ProtectedRoute.tsx
  backend/back-office/components/PublicRoute.tsx
  backend/back-office/index.html
  backend/fittoring/src/main/java/fittoring/aspect/LogAspect.java
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/DuplicatePhoneException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/InvalidCertificateException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/MentoringAlreadyExistException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/CertificateType.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MemberRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/AuthService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/CertificateService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ParticipatedReservationResponse.java
  backend/fittoring/src/main/resources/data.sql
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  frontend/src/common/apis/apiClient.ts
  frontend/src/common/components/MentoringApplicationStatus/MentoringApplicationStatus.stories.tsx
  frontend/src/common/components/MentoringApplicationStatus/MentoringApplicationStatus.tsx
  frontend/src/common/mock/createdMentoring/data.ts
  frontend/src/common/mock/participatedMentoring/data.ts
  frontend/src/common/types/statusType.ts
  frontend/src/pages/createdMentoring/components/ActionButtons/ActionButtons.stories.tsx
  frontend/src/pages/createdMentoring/components/ActionButtons/ActionButtons.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationItem/MentoringApplicationItem.stories.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationList/MentoringApplicationList.stories.tsx
  frontend/src/pages/createdMentoring/components/PhoneNumber/PhoneNumber.stories.tsx
  frontend/src/pages/createdMentoring/components/PhoneNumber/PhoneNumber.tsx
  frontend/src/pages/createdMentoring/types/mentoringApplicationStatus.ts
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/mentoringCreate/components/BaseInfoSection/BaseInfoSection.tsx
  frontend/src/pages/mentoringCreate/components/CertificateInput/CertificateInput.tsx
  frontend/src/pages/mentoringCreate/components/DetailIntroduce/DetailIntroduce.tsx
  frontend/src/pages/mentoringCreate/components/IntroduceSection/IntroduceSection.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/participatedMentoring/ReviewButton/ReviewButton.stories.tsx
  frontend/src/pages/participatedMentoring/ReviewButton/ReviewButton.tsx
Labels: 🧻 merge

#388 [FEAT] 로그인 실패시 안내문구 추가
  frontend/src/common/components/FormField/FormField.tsx
  frontend/src/pages/login/components/LoginForm/LoginForm.tsx
Labels: ❄️ FE, ☘️ feat

#390 [FIX] api 명세 및 멘토링 데이터 다시 불러오기
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/pages/createdMentoring/apis/getMenteePhoneNumber.ts
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
Labels: ❄️ FE, 🔧 fix

#407 [FIX] 예약 상태 변경 시 변경 검증 로직 수정
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Status.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/model/StatusTest.java
Labels: ✨ BE, 🔧 fix

#328 [FEAT] 멘토링 상세 페이지 탭 UI 구현
  frontend/src/common/mock/handlers.ts
  frontend/src/common/mock/mentoringDetail/data.ts
  frontend/src/common/mock/mentoringDetail/handler.ts
  frontend/src/pages/detail/Detail.tsx
  frontend/src/pages/detail/components/MentorSummary/MentorSummary.tsx
  frontend/src/pages/detail/components/Profile/Profile.tsx
  frontend/src/pages/detail/types/MentoringResponse.ts
Labels: ❄️ FE, ☘️ feat

#409 [REFACTOR] 로깅 리팩터링
  backend/fittoring/src/main/java/fittoring/aspect/LogAspect.java
  backend/fittoring/src/main/java/fittoring/config/filter/RequestWrappingFilter.java
  backend/fittoring/src/main/java/fittoring/util/JsonUtil.java
  backend/fittoring/src/main/resources/application.yml
Labels: ✨ BE, :recycle: refactor

#414 [FEAT] 관리자 페이지 개선 및 멘토링 관리 퍼블리싱
  backend/back-office/App.tsx
  backend/back-office/components/AuthContext.tsx
  backend/back-office/components/Dashboard.tsx
  backend/back-office/components/DashboardLayout.tsx
  backend/back-office/components/LoginPage.tsx
  backend/back-office/components/MentoringDetailPage.tsx
  backend/back-office/components/ProtectedRoute.tsx
  backend/back-office/components/PublicRoute.tsx
  backend/back-office/components/dashboard/CertificationManagement.tsx
  backend/back-office/components/dashboard/MentoringDetail.tsx
  backend/back-office/components/dashboard/MentoringManagement.tsx
  backend/back-office/components/ui/sidebar.tsx
  backend/back-office/components/ui/sonner.tsx
  backend/back-office/constants/config.ts
  backend/back-office/constants/routes.ts
  backend/back-office/services/authApi.ts
  backend/back-office/services/certificateApi.ts
  backend/back-office/tsconfig.app.tsbuildinfo
  backend/back-office/tsconfig.node.tsbuildinfo
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Member.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MemberService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MemberController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/AdminActiveStatusResponse.java
  backend/fittoring/src/main/resources/static/web-admin/assets/index-CEC4QTX-.css
  backend/fittoring/src/main/resources/static/web-admin/assets/index-DbAmRrn0.js
  backend/fittoring/src/main/resources/static/web-admin/assets/index-DbAmRrn0.js.map
  backend/fittoring/src/main/resources/static/web-admin/index.html
Labels: ✨ BE, ☘️ feat

#426 [MERGE] 릴리즈 브랜치 병합
  backend/back-office/App.tsx
  backend/back-office/components/AuthContext.tsx
  backend/back-office/components/Dashboard.tsx
  backend/back-office/components/DashboardLayout.tsx
  backend/back-office/components/LoginPage.tsx
  backend/back-office/components/MentoringDetailPage.tsx
  backend/back-office/components/ProtectedRoute.tsx
  backend/back-office/components/PublicRoute.tsx
  backend/back-office/components/dashboard/CertificationManagement.tsx
  backend/back-office/components/dashboard/MentoringDetail.tsx
  backend/back-office/components/dashboard/MentoringManagement.tsx
  backend/back-office/components/ui/sidebar.tsx
  backend/back-office/components/ui/sonner.tsx
  backend/back-office/constants/config.ts
  backend/back-office/constants/routes.ts
  backend/back-office/services/authApi.ts
  backend/back-office/services/certificateApi.ts
  backend/back-office/tsconfig.app.tsbuildinfo
  backend/back-office/tsconfig.node.tsbuildinfo
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Member.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/CertificateRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MemberService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReviewService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/MentoringReviewGetDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MemberController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MentoringController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ReviewController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/AdminActiveStatusResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/CertificateSpecAndImageResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringReviewGetResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringSummaryResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ReviewGetResponse.java
  backend/fittoring/src/main/resources/static/web-admin/assets/index-CEC4QTX-.css
  backend/fittoring/src/main/resources/static/web-admin/assets/index-DbAmRrn0.js
  backend/fittoring/src/main/resources/static/web-admin/assets/index-DbAmRrn0.js.map
  backend/fittoring/src/main/resources/static/web-admin/index.html
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReviewControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminCertificateControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MemberServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
Labels: 🧻 merge

#413 [FEAT] 멘토링 상세조회(자격증명) UI
  frontend/src/common/components/Header/Header.tsx
  frontend/src/common/mock/mentoringDetail/data.ts
  frontend/src/pages/detail/Detail.tsx
  frontend/src/pages/detail/components/ApplySection/ApplySection.tsx
  frontend/src/pages/detail/components/Certificates/Certificates.stories.tsx
  frontend/src/pages/detail/components/Certificates/Certificates.tsx
  frontend/src/pages/detail/components/Profile/Profile.tsx
  frontend/src/pages/detail/types/CertificatesResponse.ts
  frontend/src/pages/detail/types/MentoringResponse.ts
Labels: ❄️ FE, ☘️ feat

#429 [FEAT] 어드민 전용 예약 관리 기능 추가
  backend/fittoring/src/main/java/fittoring/config/auth/AuthenticationInterceptor.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ReviewRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/AdminReservationStatusUpdateDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/MentoringReservationGetDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminReservationController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/AdminReservationDeleteDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/AdminReservationResponse.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminReservationControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
Labels: ✨ BE, ☘️ feat

#430 [FEAT] 요청 실패에 대해 토큰 재발급 기능 및 재요청 기능 추가
  frontend/src/common/apis/ApiError.ts
  frontend/src/common/apis/apiClient.ts
  frontend/src/pages/createdMentoring/CreatedMentoring.tsx
Labels: ❄️ FE, ☘️ feat

#434 [FEAT] 관리자용 멘토링 삭제 API 개발
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/CategoryMentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Review.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/CategoryMentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminMentoringController.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
Labels: ✨ BE, ☘️ feat

#446 [FEAT] 클라이언트 오리진 추가
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
Labels: ✨ BE, ☘️ feat

#428 [FEAT] 관리자 페이지 API 연결
  backend/back-office/components/dashboard/MentoringDetail.tsx
  backend/back-office/components/dashboard/MentoringManagement.tsx
  backend/back-office/components/ui/alert-dialog.tsx
  backend/back-office/components/ui/button.tsx
  backend/back-office/components/ui/sidebar.tsx
  backend/back-office/constants/config.ts
  backend/back-office/services/apiUtils.ts
  backend/back-office/services/certificateApi.ts
  backend/back-office/services/mentoringApi.ts
  backend/back-office/services/reservationApi.ts
  backend/back-office/tsconfig.app.tsbuildinfo
  backend/fittoring/src/main/resources/static/web-admin/assets/index-DCYLnK4x.js
  backend/fittoring/src/main/resources/static/web-admin/assets/index-gqcdPxpR.css
  backend/fittoring/src/main/resources/static/web-admin/index.html
Labels: ✨ BE

#449 [BUILD] 코드래빗 도입
  .coderabbit.yaml
  config/be-code-convention.md
  config/fe-code-convention.md
Labels: 🏢 build

#432 [FEAT] 멘토링 상세조회 자격 사항 이미지 모달
  frontend/src/common/assets/images/chevron-left.svg
  frontend/src/common/assets/images/chevron-right.svg
  frontend/src/common/assets/images/white-x-mark.svg
  frontend/src/common/components/Modal/Modal.tsx
  frontend/src/common/mock/mentoringDetail/data.ts
  frontend/src/pages/detail/components/ApplySection/ApplySection.tsx
  frontend/src/pages/detail/components/Certificates/Certificates.tsx
  frontend/src/pages/detail/components/CertificatesImageModal/CertificatesImageModal.stories.tsx
  frontend/src/pages/detail/components/CertificatesImageModal/CertificatesImageModal.tsx
  frontend/src/pages/detail/types/CertificatesResponse.ts
Labels: ❄️ FE, ☘️ feat

#411 [FIX] 전화번호 인증 재요청 시 버튼 상태 및 검증 로직 개선
  frontend/src/pages/signup/components/PhoneFields/PhoneFields.tsx
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
  frontend/src/pages/signup/hooks/useVerificationCodeConfirm.ts
  frontend/src/pages/signup/hooks/useVerificationCodeRequest.ts
Labels: ❄️ FE, 🔧 fix

#444 [FEAT] 리뷰 생성 시 완료된 리뷰에만 남길 수 있도록 검증
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/ReservationNotCompletedException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Member.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Mentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Status.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReviewService.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReviewControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
Labels: ✨ BE, ☘️ feat

#454 [FEAT] 자신이 개설한 멘토링 정보 조회 기능 구현
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MentoringController.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
Labels: ✨ BE, ☘️ feat

#465 [REFACTOR] api 요청 권한 인증 방식 변경
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/java/fittoring/config/auth/AuthRequired.java
  backend/fittoring/src/main/java/fittoring/config/auth/AuthenticationInterceptor.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MemberController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MentoringController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ReservationController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ReviewController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminCertificateController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminMentoringController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminReservationController.java
Labels: ✨ BE, :recycle: refactor

#470 [Release]
  backend/back-office/components/Dashboard.tsx
  backend/back-office/components/DashboardLayout.tsx
  backend/back-office/components/LoginPage.tsx
  backend/back-office/components/dashboard/MentoringDetail.tsx
  backend/back-office/constants/config.ts
  backend/back-office/index.html
  backend/back-office/public/fittoring.png
  backend/back-office/services/reservationApi.ts
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/java/fittoring/config/auth/AuthRequired.java
  backend/fittoring/src/main/java/fittoring/config/auth/AuthenticationInterceptor.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MemberController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MentoringController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ReservationController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ReviewController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminCertificateController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminMentoringController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminReservationController.java
  backend/fittoring/src/main/resources/static/web-admin/assets/index-Bvlef40-.js
  backend/fittoring/src/main/resources/static/web-admin/assets/index-DCYLnK4x.js
  backend/fittoring/src/main/resources/static/web-admin/fittoring.png
  backend/fittoring/src/main/resources/static/web-admin/index.html
  frontend/buildspec.yml
Labels: ❄️ FE, 🏢 build

#475 [Release]
  frontend/webpack.config.js
Labels: ❄️ FE, 🔧 fix

#480 [FEAT] 자격 사항 삭제
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/ForbiddenException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/ForbiddenMemberException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/NotCertificateOwnerException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Certificate.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/CertificateService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MemberService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReviewService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/CertificateDeleteDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/CertificateController.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/CertificateServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
Labels: ✨ BE, ☘️ feat

#482 [FEAT] 로그아웃 UI 및 기능 추가
  frontend/src/common/apis/apiClient.ts
  frontend/src/common/apis/postLogout.ts
  frontend/src/common/components/AuthProvider/AuthProvider.tsx
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/pages/login/components/LoginForm/LoginForm.tsx
  frontend/src/pages/myPage/components/MenuDropDown/MenuDropDown.tsx
Labels: ❄️ FE, ☘️ feat

#489 [FIX] 메인 페이지 멘토 카드 전체 별점 평균 및 갯수 랜더링
  frontend/src/common/mock/mentoring/data.ts
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/MentorCardItem/MentorCardItem.tsx
  frontend/src/pages/home/types/MentorInformation.ts
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
Labels: ❄️ FE, 🔧 fix

#493 [STYLE] 요구사항에 따른 리뷰 디자인 변경
  frontend/src/pages/detail/components/ReviewItem/ReviewItem.tsx
Labels: ❄️ FE, 🎨 style

#500 [MERGE]
  backend/fittoring/src/main/java/fittoring/aspect/LogAspect.java
  backend/fittoring/src/main/java/fittoring/aspect/dto/ErrorLog.java
  backend/fittoring/src/main/java/fittoring/aspect/dto/RequestLog.java
  backend/fittoring/src/main/java/fittoring/aspect/dto/ResponseLog.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ReviewRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/RatingStatsDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringSummaryResponse.java
  backend/fittoring/src/main/java/fittoring/util/ResponseDurationCalculator.java
  backend/fittoring/src/main/resources/application.yml
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
Labels: ✨ BE, 🧻 merge

#496 [FEAT] 멘토링 수정 기능 구현
  frontend/src/App.tsx
  frontend/src/common/apis/apiClient.ts
  frontend/src/common/apis/getMineMentoring.ts
  frontend/src/common/apis/getUserInfoSummary.ts
  frontend/src/common/components/mentoringForm/BaseInfoSection/BaseInfoSection.stories.tsx
  frontend/src/common/components/mentoringForm/BaseInfoSection/BaseInfoSection.tsx
  frontend/src/common/components/mentoringForm/ButtonSection/ButtonSection.stories.tsx
  frontend/src/common/components/mentoringForm/ButtonSection/ButtonSection.tsx
  frontend/src/common/components/mentoringForm/CertificateInput/CertificateInput.tsx
  frontend/src/common/components/mentoringForm/CertificateSection/CertificateSection.stories.tsx
  frontend/src/common/components/mentoringForm/CertificateSection/CertificateSection.tsx
  frontend/src/common/components/mentoringForm/DetailIntroduce/DetailIntroduce.stories.tsx
  frontend/src/common/components/mentoringForm/DetailIntroduce/DetailIntroduce.tsx
  frontend/src/common/components/mentoringForm/IntroduceSection/IntroduceSection.stories.tsx
  frontend/src/common/components/mentoringForm/IntroduceSection/IntroduceSection.tsx
  frontend/src/common/components/mentoringForm/ProfileSection/ProfileSection.stories.tsx
  frontend/src/common/components/mentoringForm/ProfileSection/ProfileSection.tsx
  frontend/src/common/components/mentoringForm/SpecialtySection/SpecialtySection.stories.tsx
  frontend/src/common/components/mentoringForm/SpecialtySection/SpecialtySection.tsx
  frontend/src/common/components/mentoringForm/SpecialtyTag/SpecialtyTag.stories.tsx
  frontend/src/common/components/mentoringForm/SpecialtyTag/SpecialtyTag.tsx
  frontend/src/common/components/mentoringForm/TitleSeparator/TitleSeparator.stories.tsx
  frontend/src/common/components/mentoringForm/TitleSeparator/TitleSeparator.tsx
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/common/constants/career.ts
  frontend/src/common/constants/introduce.ts
  frontend/src/common/constants/price.ts
  frontend/src/common/constants/url.ts
  frontend/src/common/hooks/usePreviewImage.ts
  frontend/src/common/types/certificateItem.ts
  frontend/src/common/types/mentoringCreateFormData.ts
  frontend/src/common/types/userInfoResponse.ts
  frontend/src/common/utils/careerValidator.ts
  frontend/src/common/utils/introduceValidator.ts
  frontend/src/common/utils/priceValidator.ts
  frontend/src/pages/createdMentoring/CreatedMentoring.tsx
  frontend/src/pages/detail/components/ApplySection/ApplySection.tsx
  frontend/src/pages/mentoringCreate/apis/getUserInfo.ts
  frontend/src/pages/mentoringCreate/apis/postMentoringCreate.ts
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringCreate/components/ProfileSection/ProfileSection.tsx
  frontend/src/pages/mentoringUpdate/MentoringUpdate.tsx
  frontend/src/pages/mentoringUpdate/apis/putMentoring.ts
  frontend/src/pages/mentoringUpdate/components/MentoringUpdateForm/MentoringUpdateForm.tsx
  frontend/src/pages/mentoringUpdate/components/MentoringUpdateHeader/MentoringUpdateHeader.stories.tsx
  frontend/src/pages/mentoringUpdate/components/MentoringUpdateHeader/MentoringUpdateHeader.tsx
  frontend/src/pages/mentoringUpdate/types/mentoringUpdateForm.ts
  frontend/src/pages/mentoringUpdate/utils/isInitialMentoringData.ts
Labels: ❄️ FE, ☘️ feat

#526 [MERGE]
  .github/workflows/release-dev-ci-cd.yml
  backend/fittoring/docker-compose.yml
Labels: ✨ BE, 🧻 merge

#505 [FIX] 멘토링 삭제시 연관된 자격증도 삭제하도록 수정
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Certificate.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
Labels: ✨ BE, 🔧 fix

#516 [REFACTOR] 리뷰 생성 후 멘토링 id 반환하도록 수정
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReviewService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ReviewCreateResponse.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
Labels: ✨ BE, :recycle: refactor

#534 [MERGE]
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReviewService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ReviewCreateResponse.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
Labels: ✨ BE, 🔧 fix

#509 [FEAT] 아이디 중복 확인 완료시 안내 UI 구현
  frontend/src/common/styles/theme.ts
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
  frontend/src/pages/signup/components/UserIdField/UserIdField.tsx
  frontend/src/pages/signup/hooks/useUserIdDuplicateCheck.ts
Labels: ❄️ FE, ☘️ feat

#545 [BUILD] prod 서버 구축
  .github/workflows/release-prod-ci-cd.yml
  backend/fittoring/Dockerfile
Labels: ✨ BE, 🏢 build

#546 [MERGE] CI/CD 테스트를 위한 브랜치 병합
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
Labels: ✨ BE, 🏢 build

#548 [MERGE] release-prod 브랜치 병합
  .github/workflows/release-dev-ci-cd.yml
  .github/workflows/release-prod-ci-cd.yml
  backend/fittoring/Dockerfile
  backend/fittoring/docker-compose.yml
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Certificate.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/CertificateService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReviewService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ReviewCreateResponse.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
  frontend/src/common/apis/ApiError.ts
  frontend/src/common/apis/apiClient.ts
  frontend/src/common/components/AuthProvider/AuthProvider.tsx
  frontend/src/common/components/mentoringForm/BaseInfoSection/BaseInfoSection.tsx
  frontend/src/common/components/mentoringForm/ButtonSection/ButtonSection.tsx
  frontend/src/common/components/mentoringForm/CertificateSection/CertificateSection.tsx
  frontend/src/common/components/mentoringForm/SpecialtySection/SpecialtySection.tsx
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/common/styles/theme.ts
  frontend/src/common/utils/captureSentryError.ts
  frontend/src/pages/booking/Booking.tsx
  frontend/src/pages/booking/components/BookingForm/BookingForm.tsx
  frontend/src/pages/createdMentoring/CreatedMentoring.tsx
  frontend/src/pages/createdMentoring/components/ActionButtons/ActionButtons.tsx
  frontend/src/pages/detail/Detail.tsx
  frontend/src/pages/detail/components/ApplySection/ApplySection.tsx
  frontend/src/pages/detail/components/DetailReview/DetailReview.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.tsx
  frontend/src/pages/login/components/LoginForm/LoginForm.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringUpdate/apis/deleteCertificate.ts
  frontend/src/pages/mentoringUpdate/components/MentoringUpdateForm/MentoringUpdateForm.tsx
  frontend/src/pages/myPage/components/MenuDropDown/MenuDropDown.tsx
  frontend/src/pages/myPage/components/MyPageHeader/MyPageHeader.tsx
  frontend/src/pages/myPage/components/MyProfile/MyProfile.tsx
  frontend/src/pages/participatedMentoring/ParticipatedMentoring.tsx
  frontend/src/pages/participatedMentoring/ReviewModal/ReviewModal.tsx
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
  frontend/src/pages/signup/components/UserIdField/UserIdField.tsx
  frontend/src/pages/signup/hooks/useUserIdDuplicateCheck.ts
  frontend/src/pages/signup/hooks/useVerificationCodeConfirm.ts
  frontend/src/pages/signup/hooks/useVerificationCodeRequest.ts
Labels: ✨ BE, ❄️ FE, 🧻 merge

#528 [BUILD] 웹팩 환경 분리 설정
  .github/workflows/frontend-build.yml
  frontend/buildspec.yml
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: ❄️ FE, 🏢 build

#539 [FEAT] 시멘틱 버저닝 적용
  .github/workflows/semantic-release.yml
  frontend/package-lock.json
  frontend/package.json
Labels: ❄️ FE, ☘️ feat

#543 [FEAT] 개설한 멘토링이 있을 경우 "멘토링 개설하기" 버튼을 "멘토링 관리하기"로 변경
  frontend/src/pages/home/components/Slogan/Slogan.tsx
Labels: ❄️ FE, ☘️ feat

#523 [FEAT] Flyway 도입
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Offering.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/RefreshToken.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/OfferingRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/AuthService.java
  backend/fittoring/src/main/resources/application.yml
  backend/fittoring/src/main/resources/db/migration/V1__init_schema.sql
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/AuthControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/AuthServiceTest.java
  backend/fittoring/src/test/java/fittoring/util/DbCleaner.java
  backend/fittoring/src/test/resources/application-test.yml
Labels: ✨ BE, 🏢 build

#542 [FEAT] reissue 예외 추가
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/AuthService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/JwtExtractor.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/AuthControllerTest.java
Labels: ✨ BE, ☘️ feat

#551 [Release]
  .github/workflows/frontend-build.yml
  .github/workflows/semantic-release.yml
  frontend/buildspec.yml
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/detail/Detail.tsx
  frontend/src/pages/home/components/HomeHeader/HomeHeader.tsx
  frontend/src/pages/home/components/Slogan/Slogan.tsx
  frontend/src/pages/participatedMentoring/ReviewModal/ReviewModal.tsx
  frontend/webpack.common.js
  frontend/webpack.dev.js
  frontend/webpack.prod.js
Labels: 🧻 merge

#553 [BUILD] CD 속도 개선
  backend/fittoring/Dockerfile
Labels: ✨ BE, 🏢 build

#554 [MERGE]
  backend/fittoring/Dockerfile
Labels: 🧻 merge

#557 [FIX] dev 서버 CD 오류 수정
  .github/workflows/release-dev-ci-cd.yml
Labels: ✨ BE, 🔧 fix

#561 [BUILD] 웹팩 개발 및 운영 환경에 맞게 환경 변수 적용
  frontend/webpack.common.js
Labels: ❄️ FE, 🏢 build

#568 [FIX] buildspec.yml 적용 안되던 문제 해결
  frontend/buildspec.yml
Labels: ❄️ FE, 🔧 fix, 🏢 build

#567 [FIX] 인증확인 유효성 검사 로직 문제 해결
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
  frontend/src/pages/signup/hooks/useVerificationCodeConfirm.ts
Labels: ❄️ FE, 🔧 fix

#569 [MERGE]
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
  frontend/src/pages/signup/hooks/useVerificationCodeConfirm.ts
Labels: 🧻 merge

#572 [FIX] 리뷰 컨텐츠 정보 수정
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/MentorMentoringReservationResponse.java
Labels: ✨ BE, 🔧 fix
