Repository woowacourse-teams/2025-Fit-toring, pull requests merged in 2025-10, with the labels that each got.

#826 [MERGE] 6차 데모 1차 스프린트 기능 배포 (1)
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/FittoringApplication.java
  backend/fittoring/src/main/java/fittoring/config/S3Configuration.java
  backend/fittoring/src/main/java/fittoring/config/S3Properties.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/UnsupportedImageExtensionException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/ImageExtension.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Mentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/MentoringStatistics.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Review.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringStatisticsRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ReviewRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/PresignedUrlService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReviewService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/IssuedPresignedDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/ContentType.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/KeyBuilder.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/S3Uploader.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ImageController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/IssuedPresignedRequest.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/PresignedIssueResponse.java
  backend/fittoring/src/main/resources/application.yml
  backend/fittoring/src/main/resources/db/migration/V202509291557__create_mentoring_statistics.sql
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/CertificateServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MemberServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
  backend/fittoring/src/test/resources/application-test.yml
  frontend/src/pages/signup/components/PhoneFields/PhoneFields.tsx
  frontend/src/pages/signup/components/UserIdField/UserIdField.tsx
  frontend/webpack.prod.js
Labels: 🧻 merge

#816 [FEAT] 카카오 소셜 로그인을 위한 서버 로직 작성
  .github/workflows/backend-ci.yml
  .github/workflows/release-dev-ci-cd.yml
  .github/workflows/release-prod-ci-cd.yml
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/AuthProvider.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/MemberOauth.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MemberOauthRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/AuthService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/JwtProvider.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/KakaoTokenResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/KakaoUserInfoResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/OauthClientService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/CookieWriter.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/AuthController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/AuthTokenResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/OauthSignUpRequest.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/exception/OauthLoginException.java
  backend/fittoring/src/main/resources/application.yml
  backend/fittoring/src/main/resources/db/migration/V202509300951__create_member_oauth.sql
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/AuthServiceTest.java
  backend/fittoring/src/test/resources/application-test.yml
Labels: ✨ BE, ☘️ feat

#831 [FIX] RestClient Bean 분리
  backend/fittoring/src/main/java/fittoring/config/RestClientConfiguration.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/OauthClientService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsRestClientService.java
Labels: ✨ BE, 🔧 fix

#850 [FIX] 소셜 회원가입 후 로그인 버그 수정
  backend/fittoring/src/main/java/fittoring/application/auth/CookieWriter.java
  backend/fittoring/src/main/java/fittoring/application/auth/presentation/AuthController.java
Labels: ✨ BE, 🔧 fix

#836 [REFACTOR] 멘토링 개설/수정 기능 이미지 업로드 방식 개선
  backend/fittoring/src/main/java/fittoring/admin/presentation/AdminImageController.java
  backend/fittoring/src/main/java/fittoring/application/image/service/ImageService.java
  backend/fittoring/src/main/java/fittoring/application/image/service/PresignedUrlService.java
  backend/fittoring/src/main/java/fittoring/application/mentoring/presentation/MentoringController.java
  backend/fittoring/src/main/java/fittoring/application/mentoring/presentation/dto/request/CertificateInfoRequest.java
  backend/fittoring/src/main/java/fittoring/application/mentoring/presentation/dto/request/MentoringRegisterRequest.java
  backend/fittoring/src/main/java/fittoring/application/mentoring/service/CertificateService.java
  backend/fittoring/src/main/java/fittoring/application/mentoring/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/application/mentoring/service/dto/ModifyMentoringDto.java
  backend/fittoring/src/main/java/fittoring/application/mentoring/service/dto/RegisterMentoringDto.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/infrastructure/SmsAuthHeaderGenerator.java
  backend/fittoring/src/main/java/fittoring/infrastructure/SmsRestClientService.java
  backend/fittoring/src/main/java/fittoring/infrastructure/exception/InfraErrorMessage.java
  backend/fittoring/src/main/java/fittoring/infrastructure/exception/S3UploadException.java
  backend/fittoring/src/main/java/fittoring/infrastructure/exception/SmsException.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/Encoded.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/ImageConstants.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/ImageResizer.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/ImageTranscoder.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/InmemoryMultipartFile.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/KeyBuilder.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/S3Uploader.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/VariantUploadResult.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/policy/CertificatePolicy.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/policy/ImagePolicyRegistry.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/policy/ImageTypePolicy.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/policy/MentoringProfilePolicy.java
  backend/fittoring/src/main/java/fittoring/infrastructure/image/policy/NonePolicy.java
  backend/fittoring/src/main/java/fittoring/logging/JsonLogger.java
  backend/fittoring/src/main/java/fittoring/logging/dto/AppLog.java
  backend/fittoring/src/test/java/fittoring/application/member/service/MemberServiceTest.java
  backend/fittoring/src/test/java/fittoring/application/mentoring/service/CertificateServiceTest.java
  backend/fittoring/src/test/java/fittoring/application/mentoring/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/application/reservation/service/ReservationServiceTest.java
  backend/fittoring/src/test/java/fittoring/application/review/service/ReviewServiceTest.java
  backend/fittoring/src/test/java/fittoring/infrastructure/SmsRestClientServiceTest.java
  backend/fittoring/src/test/java/fittoring/integration/MentoringIntegrationTest.java
  backend/fittoring/src/test/java/fittoring/integration/admin/AdminImageIntegrationTest.java
Labels: ✨ BE, :recycle: refactor

#854 [BUILD] 애플리케이션 메트릭을 제공하는 액추에이터 경로 추가
  backend/fittoring/build.gradle
  backend/fittoring/src/main/resources/application.yml
Labels: ✨ BE, 🏢 build

#858 [FIX] develop - release-dev 브랜치 충돌 해결
  backend/fittoring/src/main/java/fittoring/application/mentoring/repository/MentoringRepository.java
  backend/fittoring/src/main/java/fittoring/application/mentoring/service/MentoringService.java
  frontend/CHANGELOG.md
Labels: 🔧 fix

#865 [FIX] /metrics 엔드포인트 추가
  backend/fittoring/src/main/resources/application.yml
Labels: ✨ BE, 🔧 fix

#822 [FEAT] 채팅방 UI 구현
  frontend/src/App.tsx
  frontend/src/common/assets/images/sendIcon.svg
  frontend/src/common/constants/url.ts
  frontend/src/common/styles/theme.ts
  frontend/src/common/utils/formatToKoreanTime.ts
  frontend/src/pages/chatRoom/ChatRoom.tsx
  frontend/src/pages/chatRoom/components/ChatBubble/ChatBubble.stories.tsx
  frontend/src/pages/chatRoom/components/ChatBubble/ChatBubble.tsx
  frontend/src/pages/chatRoom/components/ChatContent/ChatContent.stories.tsx
  frontend/src/pages/chatRoom/components/ChatContent/ChatContent.tsx
  frontend/src/pages/chatRoom/components/ChatRoomHeader/ChatRoomHeader.tsx
  frontend/src/pages/chatRoom/components/InputSection/InputSection.stories.tsx
  frontend/src/pages/chatRoom/components/InputSection/InputSection.tsx
  frontend/src/pages/chatRoom/components/MentoringActionPanel/MentoringActionPanel.stories.tsx
  frontend/src/pages/chatRoom/components/MentoringActionPanel/MentoringActionPanel.tsx
Labels: ❄️ FE, ☘️ feat
