Repository woowacourse-teams/2025-Fit-toring, pull requests merged in 2025-09, with the labels that each got.

#587 [FEAT] 관리자 페이지 UI 업데이트
  backend/back-office/components/Dashboard.tsx
  backend/back-office/components/DashboardLayout.tsx
  backend/back-office/components/dashboard/CertificationManagement.tsx
  backend/back-office/components/dashboard/MenteeManagement.tsx
  backend/back-office/components/dashboard/MentoringDetail.tsx
  backend/back-office/components/dashboard/MentoringManagement.tsx
  backend/back-office/components/ui/scroll-area.tsx
  backend/back-office/constants/config.ts
  backend/back-office/services/mentoringApi.ts
  backend/back-office/services/reviewApi.ts
  backend/back-office/tsconfig.app.tsbuildinfo
  backend/back-office/utils/Formatter.tsx
  backend/fittoring/src/main/resources/static/web-admin/assets/index-B6pnEO6w.css
  backend/fittoring/src/main/resources/static/web-admin/assets/index-Bvlef40-.js
  backend/fittoring/src/main/resources/static/web-admin/assets/index-gqcdPxpR.css
  backend/fittoring/src/main/resources/static/web-admin/index.html
Labels: ✨ BE, ☘️ feat, 🎨 style

#596 [REFACTOR] 멘토링 승인, 완료 버튼 위치 변경 및 confirm 추가
  frontend/src/pages/createdMentoring/components/ActionButtons/ActionButtons.tsx
  frontend/src/pages/createdMentoring/components/MentoringApplicationItem/MentoringApplicationItem.tsx
Labels: ❄️ FE, :recycle: refactor

#600 [FIX] PR 생성 시 TEST 항상 동작하도록 변경
  .github/workflows/frontend-vitest.yml
Labels: ❄️ FE, 🔧 fix

#601 [REFACTOR] 개발 및 운영 환경 CI를 위한 github actions의 secrets 분리
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-chromatic.yml
  .github/workflows/frontend-vitest.yml
Labels: ❄️ FE, :recycle: refactor

#577 [FEAT] RestDocs 적용, Swagger UI 적용
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/resources/static/swagger-ui/favicon-16x16.png
  backend/fittoring/src/main/resources/static/swagger-ui/favicon-32x32.png
  backend/fittoring/src/main/resources/static/swagger-ui/index.css
  backend/fittoring/src/main/resources/static/swagger-ui/index.html
  backend/fittoring/src/main/resources/static/swagger-ui/oauth2-redirect.html
  backend/fittoring/src/main/resources/static/swagger-ui/swagger-initializer.js
  backend/fittoring/src/main/resources/static/swagger-ui/swagger-ui-bundle.js
  backend/fittoring/src/main/resources/static/swagger-ui/swagger-ui-es-bundle-core.js
  backend/fittoring/src/main/resources/static/swagger-ui/swagger-ui-es-bundle.js
  backend/fittoring/src/main/resources/static/swagger-ui/swagger-ui-standalone-preset.js
  backend/fittoring/src/main/resources/static/swagger-ui/swagger-ui.css
  backend/fittoring/src/main/resources/static/swagger-ui/swagger-ui.js
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/AbstractApiDocumentationTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/AuthControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/CategoryControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MemberControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReservationControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReviewControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminCertificateControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminReservationControllerTest.java
Labels: ✨ BE, ☘️ feat

#610 [FEAT] 멘토링에 오픈 채팅 URL 필드 추가
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Mentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/ModifyMentoringDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/RegisterMentoringDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringModifyRequest.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringRegisterRequest.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringResponse.java
  backend/fittoring/src/main/resources/db/migration/V202509081857__add_chat_url_column_to_mentoring.sql
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReservationControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReviewControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminCertificateControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminReservationControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminReviewControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/repository/CategoryMentoringRepositoryTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/repository/MentoringRepositoryTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/repository/ReviewRepositoryTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/CategoryServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/CertificateServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MemberServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
  backend/fittoring/src/test/java/fittoring/util/DbCleaner.java
Labels: ✨ BE, ☘️ feat

#620 [FIX] CORS 허용 경로 추가
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/resources/static/web-admin/assets/index-CHZC8Cfr.js
Labels: ✨ BE, 🔧 fix

#623 [FIX] chmod 제거
  .github/workflows/release-dev-ci-cd.yml
Labels: ✨ BE, 🔧 fix

#626 [MERGE]
  backend/fittoring/src/test/java/fittoring/mentoring/business/model/PhoneTest.java
Labels: ✨ BE, 🧻 merge

#603 [FEAT] 멘토링 개설 및 수정 시 오픈채팅 링크 Input 추가
  frontend/src/common/components/mentoringForm/BaseInfoSection/BaseInfoSection.stories.tsx
  frontend/src/common/components/mentoringForm/BaseInfoSection/BaseInfoSection.tsx
  frontend/src/common/constants/errorMessage.ts
  frontend/src/common/types/MentoringDetail.ts
  frontend/src/common/types/mentoringCreateFormData.ts
  frontend/src/common/utils/validateChatUrl.ts
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringUpdate/components/MentoringUpdateForm/MentoringUpdateForm.tsx
  frontend/src/pages/mentoringUpdate/types/mentoringUpdateForm.ts
  frontend/src/pages/mentoringUpdate/utils/isInitialMentoringData.ts
Labels: ❄️ FE, ☘️ feat

#605 [FEAT] 검색 엔진 최적화 적용
  frontend/index.html
  frontend/public/og-image.png
  frontend/public/robots.txt
  frontend/public/sitemap.xml
Labels: ❄️ FE, ☘️ feat

#635 [FIX] CI 브랜치 경로 설정 수정
  .github/workflows/frontend-chromatic.yml
  .github/workflows/frontend-vitest.yml
Labels: ❄️ FE, 🔧 fix

#629 [BUILD] CD 시 자동으로 RestDocs 명세서 업데이트하도록 수정
  .github/workflows/release-dev-ci-cd.yml
  .github/workflows/release-prod-ci-cd.yml
Labels: ✨ BE, 🏢 build

#638 [FIX] vitest CI 수정
  .github/workflows/frontend-vitest.yml
  frontend/setupTests.ts
Labels: ❄️ FE, 🔧 fix

#636 [FEAT] 예약 완료 시 멘티에게 발송되는 SMS에 오픈 채팅 링크 추가
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationNotificationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsMessageFormatter.java
Labels: ✨ BE, ☘️ feat

#655 [FIX] SEO 설정 변경
  frontend/index.html
  frontend/public/robots.dev.txt
  frontend/public/robots.prod.txt
  frontend/public/robots.txt
  frontend/public/sitemap.xml
  frontend/webpack.common.js
Labels: ❄️ FE, 🔧 fix

#675 [REFACTOR] 리뷰 조회 시 내림차순 정렬
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReviewService.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
Labels: ✨ BE, :recycle: refactor

#683 배포
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
Labels: released

#689 배포
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-chromatic.yml
  .github/workflows/frontend-vitest.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/types/MentoringDetail.ts
  frontend/src/common/utils/addSentryBreadcrumb.ts
  frontend/src/common/utils/captureSentryError.ts
  frontend/src/main.tsx
  frontend/src/pages/booking/components/BookingForm/BookingForm.tsx
  frontend/src/pages/mentoringCreate/components/MentoringCreateForm/MentoringCreateForm.tsx
  frontend/src/pages/mentoringUpdate/components/MentoringUpdateForm/MentoringUpdateForm.tsx
  frontend/webpack.prod.js
Labels: 🧻 merge, released

#692 [FEAT] mentoring 테이블 created_at 컬럼 추가 및 마이그레이션
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Mentoring.java
  backend/fittoring/src/main/resources/db/migration/V202509181853__add_created_at_column_to_mentoring.sql
Labels: ✨ BE, ☘️ feat

#693 [DESIGN] 상세페이지 UI 개선
  frontend/src/common/assets/images/close.svg
  frontend/src/common/assets/images/photoIcon.svg
  frontend/src/common/components/CategoryTag/CategoryTag.tsx
  frontend/src/common/components/TextWithIcon/TextWithIcon.tsx
  frontend/src/common/styles/reset.ts
  frontend/src/pages/detail/Detail.tsx
  frontend/src/pages/detail/components/ApplySection/ApplySection.tsx
  frontend/src/pages/detail/components/Certificates/Certificates.tsx
  frontend/src/pages/detail/components/DetailReview/DetailReview.tsx
  frontend/src/pages/detail/components/Introduction/Introduction.tsx
  frontend/src/pages/detail/components/Profile/Profile.tsx
  frontend/src/pages/detail/components/ProfileImageModal/ProfileImageModal.stories.tsx
  frontend/src/pages/detail/components/ProfileImageModal/ProfileImageModal.tsx
  frontend/src/pages/detail/components/ProfileSection/ProfileSection.stories.tsx
  frontend/src/pages/detail/components/ProfileSection/ProfileSection.tsx
Labels: ❄️ FE, 🎨 style

#697 [FEAT] Docker 로그 파일 로테이션 설정 추가
  backend/fittoring/docker-compose.yml
Labels: ✨ BE, ☘️ feat

#698 RELEASE
  backend/fittoring/docker-compose.yml
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Mentoring.java
  backend/fittoring/src/main/resources/db/migration/V202509181853__add_created_at_column_to_mentoring.sql
  frontend/src/common/assets/images/close.svg
  frontend/src/common/assets/images/photoIcon.svg
  frontend/src/common/components/CategoryTag/CategoryTag.tsx
  frontend/src/common/components/TextWithIcon/TextWithIcon.tsx
  frontend/src/common/styles/reset.ts
  frontend/src/pages/detail/Detail.tsx
  frontend/src/pages/detail/components/ApplySection/ApplySection.tsx
  frontend/src/pages/detail/components/Certificates/Certificates.tsx
  frontend/src/pages/detail/components/DetailReview/DetailReview.tsx
  frontend/src/pages/detail/components/Introduction/Introduction.tsx
  frontend/src/pages/detail/components/Profile/Profile.tsx
  frontend/src/pages/detail/components/ProfileImageModal/ProfileImageModal.stories.tsx
  frontend/src/pages/detail/components/ProfileImageModal/ProfileImageModal.tsx
  frontend/src/pages/detail/components/ProfileSection/ProfileSection.stories.tsx
  frontend/src/pages/detail/components/ProfileSection/ProfileSection.tsx
Labels: ✨ BE, 🧻 merge

#705 [FIX] 예약 내역 목록 조회 N+1 문제 해결
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ReservationRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/ParticipatedReservationDto.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
Labels: ✨ BE, 🔧 fix

#735 [FIX] CD 과정에서 캐시 추가 자동화 코드 버그 수정
  frontend/buildspec.yml
Labels: ❄️ FE, 🔧 fix

#725 [FEAT] S3 업로드 시 이미지 리사이징, avif 확장자 변환
  backend/fittoring/Dockerfile
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Image.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/ImageType.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/ImageVariant.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ImageRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ImageService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MemberService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/S3Uploader.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/exception/InfraErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/Encoded.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/ImageConstants.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/ImageResizer.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/ImageTranscoder.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/InmemoryMultipartFile.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/S3Uploader.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/VariantUploadResult.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/policy/CertificatePolicy.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/policy/ImagePolicyRegistry.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/policy/ImageTypePolicy.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/policy/MentoringProfilePolicy.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/policy/NonePolicy.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminImageController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ImageRequest.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ImageResponse.java
  backend/fittoring/src/main/resources/db/migration/V202509240106__add_image_variant.sql
  backend/fittoring/src/main/resources/db/migration/V202509242237__expand_content_of_reservation.sql
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminImageControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/CertificateServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MemberServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
Labels: ✨ BE, ☘️ feat

#737 [MERGE]
  backend/fittoring/Dockerfile
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Image.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/ImageType.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/ImageVariant.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ImageRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ImageService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MemberService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/S3Uploader.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/exception/InfraErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/Encoded.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/ImageConstants.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/ImageResizer.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/ImageTranscoder.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/InmemoryMultipartFile.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/S3Uploader.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/VariantUploadResult.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/policy/CertificatePolicy.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/policy/ImagePolicyRegistry.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/policy/ImageTypePolicy.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/policy/MentoringProfilePolicy.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/policy/NonePolicy.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/admin/AdminImageController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ImageRequest.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ImageResponse.java
  backend/fittoring/src/main/resources/db/migration/V202509240106__add_image_variant.sql
  backend/fittoring/src/main/resources/db/migration/V202509242237__expand_content_of_reservation.sql
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminImageControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/CertificateServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MemberServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  frontend/buildspec.yml
  frontend/src/App.tsx
  frontend/src/common/apis/apiClient.ts
  frontend/src/common/constants/url.ts
  frontend/src/common/hooks/useFormattedPhoneNumber.ts
  frontend/src/common/hooks/useNameInput.ts
  frontend/src/common/mock/common/data.ts
  frontend/src/common/mock/editProfile/data.ts
  frontend/src/common/mock/editProfile/handler.ts
  frontend/src/common/mock/handlers.ts
  frontend/src/common/types/userInfo.ts
  frontend/src/pages/createdMentoring/apis/patchReservationStatus.ts
  frontend/src/pages/editProfile/EditProfile.tsx
  frontend/src/pages/editProfile/apis/patchMyProfile.ts
  frontend/src/pages/editProfile/components/EditProfileForm.stories.tsx
  frontend/src/pages/editProfile/components/EditProfileForm.tsx
  frontend/src/pages/editProfile/hooks/useGender.ts
  frontend/src/pages/editProfile/hooks/useMyProfile.ts
  frontend/src/pages/editProfile/hooks/useVerificationStep.ts
  frontend/src/pages/editProfile/types/userProfile.ts
  frontend/src/pages/myPage/components/MenuDropDown/MenuDropDown.tsx
  frontend/src/pages/signup/components/SignupForm/SignupForm.tsx
  frontend/src/pages/signup/hooks/usePasswordWithConfirmInput.ts
  frontend/src/pages/signup/hooks/useSubmitGuardWithConfirm.ts
Labels: ✨ BE, 🧻 merge

#738 [FIX] CD 과정에서 캐시 추가 자동화 코드 버그 수정
  frontend/buildspec.yml
Labels: ❄️ FE, 🔧 fix

#741 [FEAT] 랜딩 페이지 성능 개선
  frontend/src/App.tsx
  frontend/src/common/assets/images/beginner.avif
  frontend/src/common/assets/images/beginner.png
  frontend/src/common/assets/images/expert.avif
  frontend/src/common/assets/images/expert.png
  frontend/src/common/assets/images/mock.avif
  frontend/src/common/types/images.d.ts
  frontend/src/pages/landing/components/Introduce/Introduce.tsx
  frontend/src/pages/landing/components/UserLevelGuide/UserLevelGuide.tsx
  frontend/webpack.common.js
Labels: ❄️ FE, ☘️ feat

#742 [FEAT] S3 배포 스크립트 개선
  frontend/buildspec.yml
Labels: ❄️ FE, ☘️ feat

#750 [FIX] 캐싱 디렉토리 dist -> empty_artifacts로 변경
  frontend/buildspec.yml
Labels: ❄️ FE, 🔧 fix

#753 [FIX] Review 및 Reservation 엔티티 fetch 전략 최적화
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Review.java
Labels: ✨ BE, 🔧 fix

#760 [FIIX] 이미지 확장자 방식 수정
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/ImageTranscoder.java
Labels: ✨ BE, 🔧 fix

#761 [MERGE]
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/ImageTranscoder.java
Labels: ✨ BE, 🧻 merge

#772 [MERGE]
  backend/fittoring/Dockerfile
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Review.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/ImageTranscoder.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/S3Uploader.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/image/VariantUploadResult.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/admin/AdminImageControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  frontend/src/common/assets/images/beginner.avif
  frontend/src/common/assets/images/expert.avif
  frontend/src/common/assets/images/mock_resized_500.png
  frontend/src/common/assets/images/mock_resized_converted.avif
  frontend/src/pages/landing/components/Introduce/Introduce.tsx
Labels: 🧻 merge

#775 [MERGE} - release-dev
  .github/workflows/release-dev-ci-cd.yml
  .github/workflows/release-prod-ci-cd.yml
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/resources/db/migration/V202509252349__add_image_unique.sql
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/common/mock/mentoring/data.ts
  frontend/src/common/styles/reset.ts
  frontend/src/pages/detail/components/Introduction/Introduction.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/apis/getMentorListByPage.ts
  frontend/src/pages/home/components/MentorCardItem/MentorCardItem.tsx
  frontend/src/pages/home/components/MentorCardList/MentorCardList.tsx
  frontend/src/pages/home/types/MentorInformation.ts
  frontend/src/pages/home/types/MentoringByPage.ts
  frontend/src/pages/participatedMentoring/MentoringItem/MentoringItem.tsx
  frontend/src/pages/signup/components/PhoneFields/PhoneFields.tsx
  frontend/src/pages/signup/components/UserIdField/UserIdField.tsx
Labels: released

#780 [RELEASE] release 1.10.1
  .github/workflows/release-dev-ci-cd.yml
  .github/workflows/release-prod-ci-cd.yml
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/resources/db/migration/V202509252349__add_image_unique.sql
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/common/mock/mentoring/data.ts
  frontend/src/common/styles/reset.ts
  frontend/src/pages/detail/components/Introduction/Introduction.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/apis/getMentorListByPage.ts
  frontend/src/pages/home/components/MentorCardItem/MentorCardItem.tsx
  frontend/src/pages/home/components/MentorCardList/MentorCardList.tsx
  frontend/src/pages/home/types/MentorInformation.ts
  frontend/src/pages/home/types/MentoringByPage.ts
  frontend/src/pages/participatedMentoring/MentoringItem/MentoringItem.tsx
  frontend/src/pages/signup/components/PhoneFields/PhoneFields.tsx
  frontend/src/pages/signup/components/UserIdField/UserIdField.tsx
Labels: released

#782 [FIX] 무한스크롤 hotfix
  frontend/src/pages/home/Home.tsx
Labels: ❄️ FE, 🔧 fix

#783 배포
  frontend/src/pages/home/Home.tsx
Labels: 🧻 merge

#784 배포
  frontend/src/pages/home/Home.tsx
Labels: 🧻 merge

#795 [BUILD] 메트릭 모니터링 위해 actuator 설정 추가
  backend/fittoring/build.gradle
  backend/fittoring/src/main/resources/application.yml
Labels: ✨ BE, 🏢 build

#796 [MERGE]
  backend/fittoring/build.gradle
  backend/fittoring/src/main/resources/application.yml
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.tsx
Labels: 🧻 merge

#808 [FEAT] 멘토링 통계 테이블 생성
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Mentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/MentoringStatistics.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Review.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringStatisticsRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ReviewRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReviewService.java
  backend/fittoring/src/main/resources/db/migration/V202509291557__create_mentoring_statistics.sql
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReviewServiceTest.java
Labels: ✨ BE, ☘️ feat
