Repository woowacourse-teams/2025-Fit-toring, pull requests merged in 2025-07, with the labels that each got.

#2 [BUILD] 백엔드 프로젝트 세팅
  backend/fittoring/.gitattributes
  backend/fittoring/.gitignore
  backend/fittoring/build.gradle
  backend/fittoring/gradle/wrapper/gradle-wrapper.jar
  backend/fittoring/gradle/wrapper/gradle-wrapper.properties
  backend/fittoring/gradlew
  backend/fittoring/gradlew.bat
  backend/fittoring/settings.gradle
  backend/fittoring/src/main/java/com/fittoring/fittoring/FittoringApplication.java
  backend/fittoring/src/main/resources/application.properties
  backend/fittoring/src/test/java/com/fittoring/fittoring/FittoringApplicationTests.java
Labels: ✨ BE, 🏢 build

#7 [BUILD] 프론트엔드 프로젝트 세팅
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/eslint.config.mjs
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/main.tsx
  frontend/tsconfig.json
  frontend/webpack.config.js
Labels: ❄️ FE, 🏢 build

#61 [FEAT] MobileLayout 컴포넌트 구현
  frontend/src/common/components/MobileLayout.tsx
  frontend/src/common/styles/reset.ts
  frontend/src/domain/mentoring/pages/Home.tsx
Labels: ❄️ FE, ☘️ feat

#60 [REFACTOR] 패키지 리팩토링
  backend/fittoring/docker-compose.yml
  backend/fittoring/src/main/java/com/fittoring/fittoring/CategoryMentoringRepository.java
  backend/fittoring/src/main/java/com/fittoring/fittoring/ReservationRepository.java
  backend/fittoring/src/main/java/fittoring/FittoringApplication.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Category.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/CategoryMentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Certificate.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Image.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/ImageType.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Mentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Offering.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/CategoryMentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/CategoryRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/CertificateRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ImageRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/OfferingRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ReservationRepository.java
  backend/fittoring/src/test/java/fittoring/FittoringApplicationTests.java
Labels: ✨ BE, 🔨 refactor

#62 [FEAT] Header 컴포넌트 구현
  frontend/src/common/components/Header.tsx
  frontend/src/common/components/MobileLayout.tsx
Labels: ❄️ FE, ☘️ feat, 🎨 style

#63 [FEAT] Footer 컴포넌트 구현
  frontend/src/App.tsx
  frontend/src/common/components/Footer.tsx
  frontend/src/domain/mentoring/pages/Home.tsx
Labels: ❄️ FE, ☘️ feat

#64 [FEAT] 공통 Button 컴포넌트 구현
  frontend/src/App.tsx
  frontend/src/MyComponent.tsx
  frontend/src/common/components/Button/Button.stories.tsx
  frontend/src/common/components/Button/Button.tsx
  frontend/src/common/components/Footer/Footer.tsx
  frontend/src/common/components/Header/Header.tsx
  frontend/src/common/components/MobileLayout/MobileLayout.tsx
  frontend/src/common/styles/theme.ts
  frontend/src/domain/mentoring/pages/Home.tsx
  frontend/src/stories/Button.stories.ts
  frontend/src/stories/Button.tsx
  frontend/src/stories/Configure.mdx
  frontend/src/stories/Header.stories.ts
  frontend/src/stories/Header.tsx
  frontend/src/stories/Page.stories.ts
  frontend/src/stories/Page.tsx
  frontend/src/stories/assets/accessibility.png
  frontend/src/stories/assets/accessibility.svg
  frontend/src/stories/assets/addon-library.png
  frontend/src/stories/assets/assets.png
  frontend/src/stories/assets/avif-test-image.avif
  frontend/src/stories/assets/context.png
  frontend/src/stories/assets/discord.svg
  frontend/src/stories/assets/docs.png
  frontend/src/stories/assets/figma-plugin.png
  frontend/src/stories/assets/github.svg
  frontend/src/stories/assets/share.png
  frontend/src/stories/assets/styling.png
  frontend/src/stories/assets/testing.png
  frontend/src/stories/assets/theming.png
  frontend/src/stories/assets/tutorials.svg
  frontend/src/stories/assets/youtube.svg
  frontend/src/stories/button.css
  frontend/src/stories/header.css
  frontend/src/stories/page.css
Labels: ❄️ FE, ☘️ feat

#68 [REFACTOR]: 공통 Button 컴포넌트 커스텀 스타일 타입 변경
  frontend/src/common/components/Button/Button.tsx
Labels: ❄️ FE, :recycle: refactor

#67 [FEAT] 예약 신청 기능 구현
  backend/fittoring/build.gradle
  backend/fittoring/docker-compose.yml
  backend/fittoring/src/main/java/fittoring/FittoringApplication.java
  backend/fittoring/src/main/java/fittoring/config/JpaConfiguration.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Mentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/ReservationCreateDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/PhoneNumber.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/PhoneNumberValidator.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ReservationController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ReservationCreateRequest.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/ReservationCreateResponse.java
  backend/fittoring/src/main/resources/application.yml
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  backend/fittoring/src/test/java/fittoring/util/DbCleaner.java
  backend/fittoring/src/test/resources/application-test.yml
Labels: ✨ BE, ☘️ feat

#76 [FEAT] 카테고리 조회 기능 구현
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Category.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/CategoryService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/CategoryController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/CategoryResponse.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/CategoryServiceTest.java
Labels: ✨ BE, ☘️ feat

#81 [FEAT] 예약 페이지 멘토 정보 카드 UI 구현
  frontend/src/App.tsx
  frontend/src/common/assets/images/locationIcon.svg
  frontend/src/common/assets/images/starIcon.svg
  frontend/src/common/assets/images/timeIcon.svg
  frontend/src/common/components/CategoryTag/CategoryTag.stories.tsx
  frontend/src/common/components/CategoryTag/CategoryTag.tsx
  frontend/src/common/components/CategoryTags/CategoryTags.tsx
  frontend/src/common/components/TextWithIcon/TextWithIcon.tsx
  frontend/src/domain/booking/components/MentorInfoCard/MentorInfoCard.tsx
  frontend/src/domain/booking/components/MentorInfoCard/MentorInfoCart.stories.tsx
  frontend/src/domain/booking/components/ProfileImg/ProfileImg.tsx
  frontend/src/domain/booking/pages/MentoringBooking.tsx
Labels: ❄️ FE, ☘️ feat

#79 [FEAT] 예약 생성 SMS 전송 구현
  backend/fittoring/.gitignore
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/config/RestClientConfiguration.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Reservation.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/ReservationCreateDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/SmsReservationMessageDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/dto/SmsSendClientDto.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsAuthHeaderGenerator.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsMessageFormatter.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsRestClientService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/ReservationController.java
  backend/fittoring/src/main/resources/application.yml
  backend/fittoring/src/main/resources/data.sql
  backend/fittoring/src/test/java/fittoring/FittoringApplicationTests.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/SmsRestClientIntegrationTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/infra/SmsAuthHeaderGeneratorTest.java
  backend/fittoring/src/test/resources/application-test.yml
Labels: ✨ BE, ☘️ feat

#83 [REFACTOR] 폴더 구조 변경
  frontend/src/App.tsx
  frontend/src/common/constants/url.ts
  frontend/src/pages/booking/Booking.tsx
  frontend/src/pages/booking/components/MentorInfoCard/MentorInfoCard.tsx
  frontend/src/pages/booking/components/MentorInfoCard/MentorInfoCart.stories.tsx
  frontend/src/pages/booking/components/ProfileImg/ProfileImg.tsx
  frontend/src/pages/detail/Detail.tsx
  frontend/src/pages/detail/components/DetailHeader/DetailHeader.stories.tsx
  frontend/src/pages/detail/components/DetailHeader/DetailHeader.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/HomeHeader/HomeHeader.stories.tsx
  frontend/src/pages/home/components/HomeHeader/HomeHeader.tsx
Labels: ❄️ FE, :recycle: refactor

#84 [BUILD] develop-fe 브랜치 세팅
  frontend/src/App.tsx
  frontend/src/common/constants/url.ts
  frontend/src/pages/booking/Booking.tsx
  frontend/src/pages/booking/components/MentorInfoCard/MentorInfoCard.tsx
  frontend/src/pages/booking/components/MentorInfoCard/MentorInfoCart.stories.tsx
  frontend/src/pages/booking/components/ProfileImg/ProfileImg.tsx
  frontend/src/pages/detail/Detail.tsx
  frontend/src/pages/detail/components/DetailHeader/DetailHeader.stories.tsx
  frontend/src/pages/detail/components/DetailHeader/DetailHeader.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/HomeHeader/HomeHeader.stories.tsx
  frontend/src/pages/home/components/HomeHeader/HomeHeader.tsx
Labels: ❄️ FE, 🏢 build

#85 [FEAT] 메인 페이지 슬로건 컴포넌트 UI 구현
  frontend/src/common/assets/images/logo.svg
  frontend/src/common/styles/theme.ts
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/HomeHeader/HomeHeader.tsx
  frontend/src/pages/home/components/Slogan/Slogan.stories.tsx
  frontend/src/pages/home/components/Slogan/Slogan.tsx
Labels: ❄️ FE, ☘️ feat

#101 [FEAT] 기본적인 API 클라이언트 구현
  frontend/package-lock.json
  frontend/package.json
  frontend/src/common/apis/apiClient.ts
  frontend/webpack.config.js
Labels: ❄️ FE, 🏢 build

#99 [FEAT] 예외 핸들링 기능 구현
  backend/fittoring/src/main/java/fittoring/exception/ErrorResponse.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/exception/SystemErrorMessage.java
  backend/fittoring/src/main/java/fittoring/exception/SystemException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/InvalidCategoryException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/MentoringNotFoundException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsAuthHeaderGenerator.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsRestClientService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/exception/InfraErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/exception/SmsException.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/infra/SmsRestClientServiceTest.java
Labels: ✨ BE, ☘️ feat

#90 [FEAT] CI 파이프라인 구현
  .github/workflows/backend-ci.yml
  backend/fittoring/Dockerfile
  backend/fittoring/docker-compose.yml
Labels: ✨ BE, ✅ test, 🏢 build

#104 [Merge] develop BE 브랜치 머지
  .github/workflows/backend-ci.yml
  backend/fittoring/Dockerfile
  backend/fittoring/docker-compose.yml
  backend/fittoring/src/main/java/fittoring/exception/ErrorResponse.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/java/fittoring/exception/SystemErrorMessage.java
  backend/fittoring/src/main/java/fittoring/exception/SystemException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/BusinessErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/InvalidCategoryException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/exception/MentoringNotFoundException.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/CategoryMentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Image.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Mentoring.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/CategoryMentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/CategoryRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/ImageRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/repository/MentoringRepository.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/ReservationService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsAuthHeaderGenerator.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/SmsRestClientService.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/exception/InfraErrorMessage.java
  backend/fittoring/src/main/java/fittoring/mentoring/infra/exception/SmsException.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MentoringController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringResponse.java
  backend/fittoring/src/main/resources/data.sql
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/ReservationServiceTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/infra/SmsRestClientServiceTest.java
Labels: ✨ BE, 🏢 build

#108 [Merge] develop 브랜치 머지
  backend/fittoring/docker-compose.yml
Labels: ✨ BE, 🏢 build

#97 [FEAT] 예약 완료 모달 UI 구현
  frontend/src/common/assets/images/bookedIcon.svg
  frontend/src/common/components/Modal/Modal.tsx
  frontend/src/pages/booking/Booking.tsx
  frontend/src/pages/booking/components/BookingHeader/BookingHeader.tsx
  frontend/src/pages/booking/components/CompleteModal/CompleteModal.stories.tsx
  frontend/src/pages/booking/components/CompleteModal/CompleteModal.tsx
Labels: ❄️ FE, ☘️ feat

#120 [FEAT] 메인 페이지 멘토 CardList 컴포넌트 UI 구현
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/MentorCardList/MentorCardList.stories.tsx
  frontend/src/pages/home/components/MentorCardList/MentorCardList.tsx
Labels: ❄️ FE, ☘️ feat

#115 [FIX] 멘토링 조회 예외 코드 수정
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
Labels: ✨ BE, 🔧 fix

#128 [MERGE] release merge 요청
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
Labels: ✨ BE, 🧻 merge

#118 [FEAT] 상세페이지 API 연결
  frontend/src/App.tsx
  frontend/src/pages/detail/Detail.tsx
  frontend/src/pages/detail/apis/getMentoringDetail.ts
  frontend/src/pages/detail/components/ApplySection/ApplySection.stories.tsx
  frontend/src/pages/detail/components/ApplySection/ApplySection.tsx
  frontend/src/pages/detail/components/DetailHeader/DetailHeader.tsx
  frontend/src/pages/detail/components/Introduction/Introduction.tsx
  frontend/src/pages/detail/components/MentorSummary/MentorSummary.stories.tsx
  frontend/src/pages/detail/components/MentorSummary/MentorSummary.tsx
  frontend/src/pages/detail/components/Profile/Profile.stories.tsx
  frontend/src/pages/detail/components/Profile/Profile.tsx
  frontend/src/pages/detail/types/MentoringResponse.ts
Labels: ❄️ FE, ☘️ feat

#124 [FEAT] 메인 페이지 필터 모달 UI 구현
  frontend/src/common/assets/images/goIcon.svg
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/MentorOverview/MentorOverview.stories.tsx
  frontend/src/pages/home/components/MentorOverview/MentorOverview.tsx
  frontend/src/pages/home/components/SpecialtyCheckbox/SpecialtyCheckbox.stories.tsx
  frontend/src/pages/home/components/SpecialtyCheckbox/SpecialtyCheckbox.tsx
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.stories.tsx
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.tsx
  frontend/src/pages/home/components/SpecialtyFilterModalButton/SpecialtyFilterModalButton.stories.tsx
  frontend/src/pages/home/components/SpecialtyFilterModalButton/SpecialtyFilterModalButton.tsx
Labels: ❄️ FE, ☘️ feat

#113 [FEAT] CD 파이프라인 구현
  .github/workflows/backend-cd.yml
Labels: ✨ BE, 🏢 build

#133 [MERGE] release 브랜치 병합
  .github/workflows/backend-cd.yml
  backend/fittoring/build.gradle
  backend/fittoring/src/main/java/fittoring/mentoring/business/model/Category.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/CategoryController.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/CategoryControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/ReservationControllerTest.java
Labels: ✨ BE, 🧻 merge

#130 [FIX] 멘토링 단건 조회 응답 수정 #125
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MentoringController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringSummaryResponse.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/SmsRestClientIntegrationTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
Labels: ✨ BE, ☘️ feat

#134 [Merge] Request develop-be branch merge into develop branch
  backend/fittoring/src/main/java/fittoring/mentoring/business/service/MentoringService.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/api/MentoringController.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringResponse.java
  backend/fittoring/src/main/java/fittoring/mentoring/presentation/dto/MentoringSummaryResponse.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/SmsRestClientIntegrationTest.java
  backend/fittoring/src/test/java/fittoring/integration/mentoring/api/MentoringControllerTest.java
  backend/fittoring/src/test/java/fittoring/mentoring/business/service/MentoringServiceTest.java
Labels: ✨ BE, 🧻 merge

#144 [FIX] cors url 추가
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
Labels: ✨ BE, 🔧 fix

#150 [FEAT] 모든 멘토 정보 조회 API 구현
  frontend/src/common/components/Modal/Modal.tsx
  frontend/src/common/constants/apiEndpoints.ts
  frontend/src/pages/detail/apis/getMentoringDetail.ts
  frontend/src/pages/detail/components/Profile/Profile.tsx
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/apis/getMentorList.ts
  frontend/src/pages/home/apis/getSpecialties.ts
  frontend/src/pages/home/components/MentorCardItem/MentorCardItem.tsx
  frontend/src/pages/home/components/MentorCardList/MentorCardList.tsx
  frontend/src/pages/home/components/MentorDetailInfoButton/MentorDetailInfoButton.tsx
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.tsx
  frontend/src/pages/home/types/MentorInformation.ts
  frontend/src/pages/home/types/Specialty.ts
Labels: ❄️ FE, ☘️ feat

#122 [FEAT] 예약 폼 제출 및 예약 완료 모달 api 연결
  frontend/src/common/constants/url.ts
  frontend/src/pages/booking/Booking.tsx
  frontend/src/pages/booking/components/BookingForm/BookingForm.tsx
  frontend/src/pages/booking/components/BookingSummarySection/BookingSummarySection.tsx
  frontend/src/pages/booking/components/CompleteModal/CompleteModal.stories.tsx
  frontend/src/pages/booking/components/CompleteModal/CompleteModal.tsx
  frontend/src/pages/booking/types/BookingResponse.ts
Labels: ❄️ FE, ☘️ feat

#152 [STYLE] 테마 색상 정의 수정 및 컴포넌트 반영
  frontend/src/common/components/Button/Button.tsx
  frontend/src/common/components/CategoryTag/CategoryTag.tsx
  frontend/src/common/components/Header/Header.tsx
  frontend/src/common/components/Input/Input.tsx
  frontend/src/common/components/TextWithIcon/TextWithIcon.tsx
  frontend/src/common/styles/theme.ts
  frontend/src/pages/booking/components/BookingForm/BookingForm.tsx
  frontend/src/pages/booking/components/BookingHeader/BookingHeader.tsx
  frontend/src/pages/booking/components/CompleteModal/CompleteModal.tsx
  frontend/src/pages/booking/components/FormField/FormField.tsx
  frontend/src/pages/booking/components/MentorInfoCard/MentorInfoCard.tsx
  frontend/src/pages/booking/components/ProfileImg/ProfileImg.tsx
  frontend/src/pages/detail/components/ApplySection/ApplySection.tsx
  frontend/src/pages/detail/components/DetailHeader/DetailHeader.tsx
  frontend/src/pages/detail/components/Introduction/Introduction.tsx
  frontend/src/pages/detail/components/MentorSummary/MentorSummary.tsx
  frontend/src/pages/detail/components/Profile/Profile.tsx
  frontend/src/pages/home/components/MentorCardItem/MentorCardItem.tsx
  frontend/src/pages/home/components/MentorOverview/MentorOverview.tsx
  frontend/src/pages/home/components/Slogan/Slogan.tsx
  frontend/src/pages/home/components/SpecialtyCheckbox/SpecialtyCheckbox.tsx
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.tsx
  frontend/src/pages/home/components/SpecialtyFilterModalButton/SpecialtyFilterModalButton.tsx
Labels: ❄️ FE, 🎨 style

#156 [FIX] Font 파일 재설정
  frontend/.storybook/preview.tsx
  frontend/src/common/assets/fonts/Pretendard-Bold.woff2
  frontend/src/common/assets/fonts/Pretendard-Regular.woff2
  frontend/src/common/components/TextWithIcon/TextWithIcon.tsx
  frontend/src/common/styles/fonts.ts
  frontend/src/common/styles/reset.ts
  frontend/src/common/styles/theme.ts
  frontend/src/pages/home/components/MentorCardItem/MentorCardItem.tsx
Labels: ❄️ FE, 🔧 fix

#158 [REFACTOR] Storybook 전역 설정
  .github/workflows/chromatic.yml
  frontend/.storybook/main.ts
  frontend/.storybook/preview.tsx
  frontend/src/common/components/Button/Button.stories.tsx
  frontend/src/common/components/CategoryTag/CategoryTag.stories.tsx
  frontend/src/common/components/Input/Input.stories.tsx
  frontend/src/common/components/Modal/Modal.stories.tsx
  frontend/src/pages/booking/components/BookingForm/BookingForm.stories.tsx
  frontend/src/pages/booking/components/BookingHeader/BookingHeader.stories.tsx
  frontend/src/pages/booking/components/BookingSummarySection/BookingSummarySection.stories.tsx
  frontend/src/pages/booking/components/CompleteModal/CompleteModal.stories.tsx
  frontend/src/pages/booking/components/MentorInfoCard/MentorInfoCart.stories.tsx
  frontend/src/pages/detail/components/ApplySection/ApplySection.stories.tsx
  frontend/src/pages/detail/components/DetailHeader/DetailHeader.stories.tsx
  frontend/src/pages/detail/components/Introduction/Introduction.stories.tsx
  frontend/src/pages/detail/components/MentorSummary/MentorSummary.stories.tsx
  frontend/src/pages/detail/components/Profile/Profile.stories.tsx
  frontend/src/pages/home/components/HomeHeader/HomeHeader.stories.tsx
  frontend/src/pages/home/components/MentorCardItem/MentorCardItem.stories.tsx
  frontend/src/pages/home/components/MentorCardList/MentorCardList.stories.tsx
  frontend/src/pages/home/components/MentorDetailInfoButton/MentorDetailInfoButton.stories.tsx
  frontend/src/pages/home/components/MentorOverview/MentorOverview.stories.tsx
  frontend/src/pages/home/components/Slogan/Slogan.stories.tsx
  frontend/src/pages/home/components/SpecialtyCheckbox/SpecialtyCheckbox.stories.tsx
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.stories.tsx
  frontend/src/pages/home/components/SpecialtyFilterModalButton/SpecialtyFilterModalButton.stories.tsx
Labels: ❄️ FE, 🏢 build

#168 [BUILD] 멘토링 목 데이터 추가
  backend/fittoring/src/main/java/fittoring/config/WebConfig.java
  backend/fittoring/src/main/resources/data.sql
Labels: ✨ BE, 🏢 build

#177 [BUILD] 프론트엔드 CI 구별
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-chromatic.yml
  .github/workflows/frontend-vitest.yml
Labels: ❄️ FE, 🏢 build

#197 [BUILD] 프론트엔드 CI 경로 설정
  .github/workflows/frontend-build.yml
  .github/workflows/frontend-chromatic.yml
  .github/workflows/frontend-vitest.yml
Labels: ❄️ FE, 🏢 build

#166 [FEAT] 멘토링 예약 신청 폼 예외처리 추가
  frontend/__tests__/getPhoneNumberErrorMessage.test.ts
  frontend/__tests__/useMenteeNameInput.test.tsx
  frontend/src/pages/booking/components/BookingForm/BookingForm.tsx
  frontend/src/pages/booking/constants/errorMessage.ts
  frontend/src/pages/booking/constants/name.ts
  frontend/src/pages/booking/hooks/useMenteeNameInput.ts
  frontend/src/pages/booking/utils/phoneNumberValidator.ts
Labels: ❄️ FE, ☘️ feat

#178 [BUILD] eslint 설정 추가
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/src/pages/booking/hooks/useFormattedPhoneNumber.ts
  frontend/src/pages/home/components/HomeHeader/HomeHeader.stories.tsx
  frontend/src/pages/home/components/SpecialtyFilterModal/SpecialtyFilterModal.tsx
Labels: ❄️ FE, 🏢 build

#215 [FEAT] 로깅 전략 추가
  backend/fittoring/src/main/resources/application.yml
Labels: ✨ BE, 🏢 build

#218 [MERGE] 로깅 전략 배포
  backend/fittoring/src/main/resources/application.yml
Labels: ✨ BE, 🧻 merge

#220 [FEAT] 도커 볼륨 마운트
  backend/fittoring/docker-compose.yml
  backend/fittoring/src/main/java/fittoring/aspect/LogAspect.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/resources/application.yml
Labels: ✨ BE, 🏢 build

#221 [MERGE] 도커 마운트 배포
  backend/fittoring/docker-compose.yml
  backend/fittoring/src/main/java/fittoring/aspect/LogAspect.java
  backend/fittoring/src/main/java/fittoring/exception/GlobalExceptionHandler.java
  backend/fittoring/src/main/resources/application.yml
Labels: ✨ BE, 🧻 merge

#205 [REFACTOR] 메인 페이지 슬로건 수정
  frontend/src/pages/home/Home.tsx
  frontend/src/pages/home/components/Slogan/Slogan.tsx
Labels: ❄️ FE, :recycle: refactor

#222 [FEAT] 회원가입 페이지 상단 UI(SignUpIntro + Header) 구현
  frontend/src/App.tsx
  frontend/src/common/constants/url.ts
  frontend/src/pages/signup/Signup.tsx
  frontend/src/pages/signup/components/SignupHeader/SignupHeader.tsx
  frontend/src/pages/signup/components/SignupIntro/SignupIntro.stories.tsx
  frontend/src/pages/signup/components/SignupIntro/SignupIntro.tsx
Labels: ❄️ FE, ☘️ feat
